### ISSUE TITLE
What replaces Keyvault?

### ISSUE THREAD

**Issue by gmyx** [canada-ca-terraform-modules/terraform-azurerm-basicwindowsvm#10]
What replaces Keyvault in the tf files? I still need a way to securely enter passwords.

**Comment by bernardmaltais** [comment]
The idea behind removing the handling of keyvault secrets is that is result in the same net result when deploying with the module.

The keyvault support is not actually removed... just how you obtain the keyvault secrets. Instead of adding this task in the module it is prefered to be done in the terraform template that call the module. Thais way the module is generic in nature and will accept a username and a password for the admin account. At the end of the day this is what the "azurerm_virtual_machine" provider accept anyway.

So now, use something like:

${azurerm_key_vault_secret.fwpassword.name}

to receive the secret from keyvault.

**Comment by bernardmaltais** [comment]
Also... I was torn about making this change and the resource naming convention change also... as the result is that using the newer version of this template will want to destroy and deploy new resources with the new names...

But I opted to change it now before it was really really too late. Only a few are using the templates right now and I felt the impact would be limited... but I might have been wrong. This point to the importance of using a good naming standard early on when defining those modules because any changes will be impact-full on users.

**Comment by gmyx** [comment]
Makes sense. This does require the user to know how to make the link - it's not as intuitive as before. Maybe it will help with my domain join problem (probably not).

**Comment by bernardmaltais** [comment]
Essentially if you create the keyvault in the same terraform deployment then accessing the secret is as easy as refering to it. For example, you you created a secret called fwpassword in keyvault you refer to it  with "${azurerm_key_vault_secret.fwpassword.name}"

If the keyvault was created outside the terraform deployment then you need to fefer to it using a data resource as documented here:

https://www.terraform.io/docs/providers/azurerm/d/key_vault.html

and

https://www.terraform.io/docs/providers/azurerm/d/key_vault_secret.html
